steps:
  # FRONTEND
  - name: node:16.13.0
    id: 'install'
    entrypoint: npm
    args: ['install']
    waitFor: ['-']

  - name: node:16.13.0
    id: 'lint'
    entrypoint: npm
    args: ['run', 'lint']
    waitFor: ['install']

  - name: node:16.13.0
    id: 'build'
    entrypoint: npm
    args: ['run', 'build']
    waitFor: ['lint']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy'
    args: ['app', 'deploy', 'app.staging.yaml']
    waitFor: ['build']
timeout: 1200s
